//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AESImplementation.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfChar", Namespace="http://tempuri.org/", ItemName="char")]
    [System.SerializableAttribute()]
    public class ArrayOfChar : System.Collections.Generic.List<char> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name RandomKeyResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RandomKey", ReplyAction="*")]
        AESImplementation.ServiceReference1.RandomKeyResponse RandomKey(AESImplementation.ServiceReference1.RandomKeyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RandomKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RandomKey", Namespace="http://tempuri.org/", Order=0)]
        public AESImplementation.ServiceReference1.RandomKeyRequestBody Body;
        
        public RandomKeyRequest() {
        }
        
        public RandomKeyRequest(AESImplementation.ServiceReference1.RandomKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RandomKeyRequestBody {
        
        public RandomKeyRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RandomKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RandomKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public AESImplementation.ServiceReference1.RandomKeyResponseBody Body;
        
        public RandomKeyResponse() {
        }
        
        public RandomKeyResponse(AESImplementation.ServiceReference1.RandomKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RandomKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AESImplementation.ServiceReference1.ArrayOfChar RandomKeyResult;
        
        public RandomKeyResponseBody() {
        }
        
        public RandomKeyResponseBody(AESImplementation.ServiceReference1.ArrayOfChar RandomKeyResult) {
            this.RandomKeyResult = RandomKeyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : AESImplementation.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<AESImplementation.ServiceReference1.Service1Soap>, AESImplementation.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AESImplementation.ServiceReference1.RandomKeyResponse AESImplementation.ServiceReference1.Service1Soap.RandomKey(AESImplementation.ServiceReference1.RandomKeyRequest request) {
            return base.Channel.RandomKey(request);
        }
        
        public AESImplementation.ServiceReference1.ArrayOfChar RandomKey() {
            AESImplementation.ServiceReference1.RandomKeyRequest inValue = new AESImplementation.ServiceReference1.RandomKeyRequest();
            inValue.Body = new AESImplementation.ServiceReference1.RandomKeyRequestBody();
            AESImplementation.ServiceReference1.RandomKeyResponse retVal = ((AESImplementation.ServiceReference1.Service1Soap)(this)).RandomKey(inValue);
            return retVal.Body.RandomKeyResult;
        }
    }
}
